# Generated by Django 6.0.3 on 2026-03-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_composicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='data_atualizacao',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=20, help_text='O sistema vai alertar se o estoque ficar abaixo disso.'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, help_text='Para matérias-primas, digite o custo. Para produtos finais, pode deixar 0 (será calculado).', max_digits=10),
        ),
    ]
