# Generated by Django 6.0.3 on 2026-04-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contapagar_contareceber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.FloatField(default=10, help_text='Quantidade mínima para disparar o alerta'),
        ),
    ]
