# Generated by Django 6.0.3 on 2026-04-07 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_produto_estoque_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade planejada para produção')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateField(help_text='Prazo de entrega / finalização')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente (Aguardando)'), ('Em Andamento', 'Em Andamento (Produzindo)'), ('Concluido', 'Concluído (No Estoque)'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, help_text='Ex: Lote especial para Cliente X', null=True)),
                ('produto', models.ForeignKey(help_text='Produto final a ser fabricado', on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
