# Generated by Django 6.0.3 on 2026-04-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_estoque_estoque_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
