# Generated by Django 6.0.4 on 2026-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_ordemproducao_custo_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemproducao',
            name='custo_historico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
