# Generated by Django 6.0.4 on 2026-04-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ordemproducao_custo_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamentoproducao',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='core.ordemproducao'),
        ),
        migrations.AddField(
            model_name='apontamentoproducao',
            name='quantidade_produzida',
            field=models.IntegerField(default=0, help_text='Quanto já foi fabricado desta OP'),
        ),
        migrations.AlterField(
            model_name='apontamentoproducao',
            name='quantidade',
            field=models.IntegerField(help_text='Quantidade produzida neste apontamento'),
        ),
    ]
