# Generated by Django 6.0.4 on 2026-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_apontamentoproducao_op_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apontamentoproducao',
            name='quantidade_produzida',
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='quantidade_produzida',
            field=models.IntegerField(default=0, help_text='Quanto já foi fabricado desta OP'),
        ),
    ]
