# Generated by Django 6.0.4 on 2026-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_fornecedor_cep_fornecedor_cidade_fornecedor_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ ou CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, help_text='Sigla. Ex: MG, SP', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual (IE)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Rua, Número, Bairro'),
        ),
    ]
