# Generated by Django 6.0.3 on 2026-03-25 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apontamentoproducao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.DecimalField(decimal_places=4, help_text='Quantidade desta matéria-prima usada para fazer 1 unidade do produto final', max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_em', to='core.produto')),
                ('produto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='core.produto')),
            ],
        ),
    ]
