# Generated by Django 6.0.3 on 2026-03-31 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_venda_itemvenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade perdida/descartada')),
                ('motivo', models.CharField(choices=[('Defeito de Fabricação', 'Defeito de Fabricação'), ('Validade Vencida', 'Validade Vencida'), ('Avaria no Manuseio', 'Avaria no Manuseio'), ('Problema na Matéria-Prima', 'Problema na Matéria-Prima'), ('Outros', 'Outros')], max_length=50)),
                ('observacao', models.TextField(blank=True, help_text='Detalhes adicionais (opcional)', null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(help_text='Produto final ou Matéria-prima', on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
