# Generated by Django 6.0.3 on 2026-04-01 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_registroperda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Empresa ou Fazenda', max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao', models.TextField(blank=True, help_text='Detalhes de contato, endereço, etc.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(help_text='Quantidade que entrou')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço pago por unidade/kg', max_digits=10)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(help_text='Matéria-prima comprada', on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor')),
            ],
        ),
    ]
