# Generated by Django 6.0.3 on 2026-04-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fornecedor_comprainsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Boleto Fazenda X, Conta de Luz', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(blank=True, help_text='Vincular a uma compra (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comprainsumo')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Venda #15 - Cliente João', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Recebido', 'Recebido')], default='Pendente', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('venda', models.ForeignKey(blank=True, help_text='Vincular a uma venda (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.venda')),
            ],
        ),
    ]
