# Generated by Django 6.0.3 on 2026-04-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_logproducao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='estoque_minimo',
            field=models.FloatField(default=10),
        ),
    ]
