# Generated by Django 6.0.3 on 2026-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ordemproducao_data_fim_ordemproducao_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço de venda (apenas para produtos finais)', max_digits=10, null=True),
        ),
    ]
