# Generated by Django 6.0.4 on 2026-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_produto_preco_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='custo_historico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo unitário real no momento da conclusão', max_digits=10, null=True),
        ),
    ]
