# Generated by Django 6.0.4 on 2026-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_apontamentoproducao_quantidade_produzida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ ou CPF'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, help_text='Para envio de pedidos de compra', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua, Número, Bairro'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, help_text='Sigla. Ex: MG, SP', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual (IE)'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(help_text='Razão Social ou Nome Fantasia', max_length=150),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='observacao',
            field=models.TextField(blank=True, help_text='Dados bancários para PIX/Boleto, prazos de pagamento, etc.', null=True),
        ),
    ]
