# Generated by Django 6.0.3 on 2026-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cliente_cep_cliente_cidade_cliente_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Diário de bordo / Anotações do comercial', null=True),
        ),
    ]
