# Generated by Django 6.0.3 on 2026-04-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cliente_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente', verbose_name='Cliente Destino (Opcional)'),
        ),
    ]
