# Generated by Django 6.0.4 on 2026-04-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ordemproducao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Logistica', 'Logística'), ('Qualidade', 'Qualidade'), ('Producao', 'Produção'), ('Financeiro', 'Financeiro'), ('Gerente', 'Gerente (Superadmin)'), ('Socios', 'Sócios (Apenas BI)')], default='Vendedor', max_length=20),
        ),
    ]
