# Generated by Django 6.0.4 on 2026-06-16 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_perfil_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_digitado', models.CharField(max_length=200, verbose_name='Nome digitado pelo cliente')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente (Aguardando Análise)'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='Pendente', max_length=20)),
                ('cliente_vinculado', models.ForeignKey(blank=True, help_text='Vincule ao cliente real após a análise', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.solicitacaopedido')),
            ],
        ),
    ]
