# Generated by Django 6.0.4 on 2026-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_solicitacaopedido_itemsolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_estoque_percentual',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Limite de Estoque (%)'),
        ),
    ]
